baseURL = "https://kasniaproject.us.kg/"
languageCode = "es"
title = "Kasnia Project"

disableKinds = ["taxonomy", "section"]

[params]
  description = "Grupo de traducción de novelas ligeras del inglés al español."
  author = "Kasnia Project"
  descargasBaseURL = "https://descargas.kasniaproject.us.kg"

[permalinks]
  novelas = "/:contentbasename/"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  404 = ["HTML"]

[minify]
  disableHTML = false
  disableCSS = false
  disableJS = false
  disableJSON = false
  disableXML = false
  disableSVG = false

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"